// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbECOaA-3eC5MQasl7K12h0drKkm4rKfc',
    appId: '1:751846261054:web:29d46acb9a6c102d056c6f',
    messagingSenderId: '751846261054',
    projectId: 'dutch-game-1dd01',
    authDomain: 'dutch-game.me',
    storageBucket: 'dutch-game-1dd01.firebasestorage.app',
    measurementId: 'G-SXR0DN53BW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH0yDjB0v_qU0Him383AoRVC3bI5oP-to',
    appId: '1:751846261054:android:b36dc858eaeb77ef056c6f',
    messagingSenderId: '751846261054',
    projectId: 'dutch-game-1dd01',
    storageBucket: 'dutch-game-1dd01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcfxXvhaAxn4GyGgqsn4DEbVaYwVtUGrA',
    appId: '1:751846261054:ios:55bf37868bd96d55056c6f',
    messagingSenderId: '751846261054',
    projectId: 'dutch-game-1dd01',
    storageBucket: 'dutch-game-1dd01.firebasestorage.app',
    iosBundleId: 'com.max.dutchGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcfxXvhaAxn4GyGgqsn4DEbVaYwVtUGrA',
    appId: '1:751846261054:ios:a4bf72265f60f5ca056c6f',
    messagingSenderId: '751846261054',
    projectId: 'dutch-game-1dd01',
    storageBucket: 'dutch-game-1dd01.firebasestorage.app',
    iosBundleId: 'com.example.dutchGame',
  );
}
