// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtKT2FJRKax7KtsNX65-J8RbTvO1w8fVM',
    appId: '1:143424334887:web:e540c11d1234d47ce1f202',
    messagingSenderId: '143424334887',
    projectId: 'dutch-game-max',
    authDomain: 'dutch-game.me',
    storageBucket: 'dutch-game-max.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvZkwvCD2uyt5yalhghPeabuYAgsM6v5Q',
    appId: '1:143424334887:android:e05e9df5c9528057e1f202',
    messagingSenderId: '143424334887',
    projectId: 'dutch-game-max',
    storageBucket: 'dutch-game-max.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbPmhH7D7BjPhTnyM11G18_j7fQ2FeAGU',
    appId: '1:143424334887:ios:b412b57e55c6fcbce1f202',
    messagingSenderId: '143424334887',
    projectId: 'dutch-game-max',
    storageBucket: 'dutch-game-max.firebasestorage.app',
    iosBundleId: 'com.max.dutchGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbPmhH7D7BjPhTnyM11G18_j7fQ2FeAGU',
    appId: '1:143424334887:ios:15f1e93ca47421d9e1f202',
    messagingSenderId: '143424334887',
    projectId: 'dutch-game-max',
    storageBucket: 'dutch-game-max.firebasestorage.app',
    iosBundleId: 'com.example.dutchGame',
  );
}
